apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: task2
spec:
  selector:
    app: task2
  ports:
    - protocol: "TCP"
      port: 9090 # The port that the service is running on in the cluster
      targetPort: 9090 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: task2
spec:
  selector:
    matchLabels:
      app: task2
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
        - name: handling-data
          image: task2 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090 # The port that the container is running on in the cluster
          args: ["--generating.url=http://10.99.20.251:8080/"]